version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    open-pull-requests-limit: 5
    versioning-strategy: auto
    schedule:
      interval: weekly
    reviewers:
      - "ViZhe"
    assignees:
      - "ViZhe"
    labels:
      - "pr: dependencies"
    commit-message:
      prefix: "build"
      include: "scope"
