name: Clippy check

on:
  pull_request:

  push:
    branches:
      - main

jobs:
  clippy_check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: Clippy check on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: lint
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
