name: Security audit

on:
  schedule:
    - cron: "0 8 * * *"

  push:
    paths:
      - "**/Cargo.*"

  pull_request:
    branches:
      - main

jobs:
  security_audit:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: Audit on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
