name: Security audit

on:
  schedule:
    - cron: "0 8 * * *"

  push:
    paths:
      - "**/Cargo.*"

  pull_request:
    branches:
      - main

jobs:
  security_audit_linux:
    name: Audit on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  security_audit_macos:
    name: Audit on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  security_audit_windows:
    name: Audit on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
